import os
import pyttsx3

# Config from config.yaml
VOICE_NAME = "Microsoft An"
RATE = 140  # Slowed down slightly for clarity

# Text content with explicit punctuation for pauses
TEXT_DOI_TUONG = """Đối tượng tác chiến của quân đội nhân dân Việt Nam. ...

Đối tượng tác chiến của quân đội nhân dân Việt Nam hiện nay là: ...
Bất cứ lực lượng nào có âm mưu và hành động chống phá mục tiêu của cách mạng nước ta; ...
tiến hành chiến tranh xâm lược; ...
diễn biến hòa bình, bạo loạn lật đổ, bạo loạn vũ trang ở nước ta; ...
xâm phạm độc lập, chủ quyền, thống nhất, toàn vẹn lãnh thổ, ...
lợi ích quốc gia - dân tộc của Việt Nam ...
thì lực lượng đó là đối tượng tác chiến của quân đội ta. ...

Hiện nay xác định ba nhóm đối tượng: ...

Nhóm thứ nhất. . . ...
Bất cứ thế lực nào có âm mưu và hành động tiến hành chiến tranh xâm lược nước ta ...
dưới bất kỳ hình thức nào. ...

Nhóm thứ hai. . . ...
Bất cứ thế lực nào có âm mưu và hành động thực hiện diễn biến hòa bình, ...
gây bạo loạn lật đổ, bạo loạn vũ trang ở nước ta. ...

Nhóm thứ ba. . . ...
Bất cứ thế lực nào có âm mưu và hành động xâm phạm độc lập, chủ quyền, thống nhất, toàn vẹn lãnh thổ của Việt Nam, ...
xâm phạm lợi ích quốc gia - dân tộc ...
bằng phương thức vũ trang hoặc phi vũ trang, ...
kể cả bên trong và bên ngoài. ...

Bốn đối tượng cụ thể bao gồm: ...

Một. . . ...
Lực lượng vũ trang hiếu chiến xâm lược, đồng minh và tay sai. ...
Đối tượng cơ bản lâu dài. ...

Hai. . . ...
Lực lượng vũ trang nước lớn và chư hầu ...
có tham vọng và hành động xâm phạm chủ quyền lãnh thổ ...
và lợi ích quốc gia dân tộc. ...
Đối tượng trực tiếp nguy hiểm. ...

Ba. . . ...
Lực lượng vũ trang phản động từ hướng tây, tây nam ...
cấu kết với lực lượng phản động trong nước xâm chiếm biên giới. ...

Bốn. . . ...
Tổ chức phản động trong và ngoài nước ...
tiến hành khủng bố vũ trang, bạo loạn vũ trang, ...
tiến hành lật đổ, ly khai đối với Việt Nam. ..."""

def generate(text, filename):
    print(f"Generating {filename}...")
    engine = pyttsx3.init()
    engine.setProperty('rate', RATE)
    
    # Find voice
    voices = engine.getProperty('voices')
    voice_found = False
    for voice in voices:
        if VOICE_NAME in voice.name or VOICE_NAME in voice.id:
            engine.setProperty('voice', voice.id)
            print(f"Using voice: {voice.name}")
            voice_found = True
            break
    
    if not voice_found:
        print(f"Warning: Voice '{VOICE_NAME}' not found. Using default.")

    # Save to file
    import pythoncom
    try:
        pythoncom.CoInitialize()
        engine.save_to_file(text, filename)
        engine.runAndWait()
        del engine
    except Exception as e:
        print(f"Error: {e}")
    finally:
        pythoncom.CoUninitialize()
        
    print(f"Done: {filename}")

def main():
    # Abs paths are safer for pyttsx3 sometimes
    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.join(base_dir, "data", "audio_static")
    os.makedirs(output_dir, exist_ok=True)
    
    generate(TEXT_DOI_TUONG, os.path.join(output_dir, "4_doi_tuong_tac_chien.wav"))

if __name__ == "__main__":
    main()
