import os
import pyttsx3

# Config
VOICE_NAME = "Microsoft An"
RATE = 130  # Slower for long historical content

# Full text with pauses from original file
TEXT_LICH_SU_QK3_FULL = """Lịch sử hình thành Quân khu ba. ...

Phần a. Khái quát về địa bàn Quân khu. ...

Vùng đất Quân khu ba ...
là địa bàn chiến lược quan trọng ...
về kinh tế, chính trị, văn hóa xã hội, quốc phòng an ninh, ...
là trung tâm của đồng bằng Bắc bộ, ...
có thế mạnh về công, nông, lâm, ngư nghiệp, ...
có núi rừng hiểm trở, có biển, hải đảo rộng lớn, ...
có hệ thống giao thông rất thuận lợi ...
trong giao lưu giữa Quân khu với Thủ đô Hà Nội ...
và nhiều vùng trọng yếu khác trong nước và quốc tế. ...

Do yêu cầu nhiệm vụ cách mạng, ...
địa bàn Quân khu ba ...
từ tháng chín, năm một nghìn chín trăm chín mươi chín về trước ...
gồm cả các tỉnh: Thanh Hoá, tỉnh Hà Bắc, tỉnh Hà Tây. ...
Từ tháng mười, năm một nghìn chín trăm chín mươi chín đến nay, ...
Quân khu ba gồm chín tỉnh, thành phố là: ...
Quảng Ninh, Hải Phòng, Thái Bình, Nam Định, ...
Hà Nam, Ninh Bình, Hoà Bình, Hải Dương và Hưng Yên. ...

Quân khu ba, ...
cái nôi của nền văn minh Sông Hồng, ...
mảnh đất địa linh nhân kiệt; ...
nơi có truyền thống yêu nước, đấu tranh bất khuất, kiên cường chống ngoại xâm. ...
Nơi sinh ra những nhà văn hoá, khoa học lỗi lạc như: ...
Mạc Đĩnh Chi, Lương Thế Vinh, Nguyễn Bỉnh Khiêm, ...
Đoàn Thị Điểm, Lê Hữu Trác, Lê Quý Đôn, Ngô Thì Nhậm, ...
và là quê hương của nhiều nhà hoạt động chính trị nổi tiếng: ...
Cố Tổng Bí thư Trường Chinh, Nguyễn Văn Linh, Nguyễn Đức Cảnh. ...

Địa bàn Quân khu ba ...
có diện tích tự nhiên hai mươi nghìn ba trăm mười bốn phẩy bảy mươi ba kilômét vuông, ...
phía Bắc và Đông Bắc tiếp giáp Trung Quốc, ...
phía Tây và Tây Nam tiếp giáp vùng Tây Bắc, ...
phía Nam tiếp giáp Bắc Trung Bộ; ...
phía đông tiếp giáp Vịnh Bắc Bộ ...
với hơn năm trăm kilômét bờ biển ...
và trên ba nghìn hòn đảo lớn nhỏ. ...
Về hành chính, các tỉnh, thành phố có chín mươi hai quận, huyện, thị xã, ...
dân số gần mười ba triệu người, ...
có trên hai mươi dân tộc anh em chung sống. ...

Vùng đất Quân khu ba ...
có nhiều danh lam thắng cảnh mang tầm vóc quốc tế như: ...
Vịnh Hạ Long, tỉnh Quảng Ninh, Di sản thiên nhiên thế giới; ...
đảo Cát Bà, thành phố Hải Phòng, Vùng dự trữ sinh quyển thế giới; ...
Tràng An, tỉnh Ninh Bình, Di sản văn hóa và thiên nhiên thế giới. ...

Địa bàn Quân khu có nhiều nhà máy, khu công nghiệp lớn; ...
có hệ thống giao thông đường sắt, thủy, bộ, hàng không ...
nối liền trong nước và quốc tế. ...

Từ vị trí địa lý, lịch sử đất và người Quân khu ba, ...
Đại tướng Võ Nguyên Giáp đã khẳng định: ...
Quân khu ba, Quân khu đồng bằng, án ngữ Thủ đô, ...
dựa vào Tây Bắc và Việt Bắc, ...
nối liền đất Thanh, Nghệ miền Trung, ...
lại nhìn ra biển cả, giàu tài nguyên và quan trọng về chiến lược. ...
Thời bình đây là một trong những vùng đất căn bản để xây dựng và phát triển, ...
là cửa ngõ giao lưu quốc tế của đất nước. ...
Thời chiến đây là hậu phương quốc gia, ...
đồng thời là mặt trận chống quân xâm lược, ...
nhiều tên làng, tên đất, tên sông ...
đã trở thành tên gọi của những chiến công hiển hách. ...

Phần b. Sự hình thành, phát triển của lực lượng vũ trang Quân khu ba. ...

Ngày ba, tháng hai, năm một nghìn chín trăm ba mươi, ...
Đảng Cộng sản Việt Nam ra đời, ...
chấm dứt thời kỳ khủng hoảng về đường lối ...
từ khi thực dân Pháp xâm lược nước ta. ...
Dưới sự lãnh đạo của Đảng, ...
trên địa bàn Quân khu đã hình thành các tổ chức bán vũ trang, vũ trang ...
ở các khu công nghiệp. ...

Ngày mười, tháng năm, năm một nghìn chín trăm bốn mươi mốt, ...
dưới sự chủ trì của Chủ tịch Hồ Chí Minh, ...
Hội nghị Ban Chấp hành Trung ương Đảng lần thứ tám ...
đã chỉ rõ: Dùng khởi nghĩa vũ trang ...
để đập tan bộ máy thống trị của thực dân Pháp, phát xít Nhật ...
giành chính quyền về tay Nhân dân. ...

Ngày hai hai, tháng mười hai, năm một nghìn chín trăm bốn mươi bốn, ...
tại khu rừng giữa hai tổng Hoàng Hoa Thám và Trần Hưng Đạo ...
thuộc châu Nguyên Bình tỉnh Cao Bằng, ...
Đội Việt Nam tuyên truyền giải phóng quân, ...
Đội quân vũ trang cách mạng đầu tiên ...
dưới sự lãnh đạo của Đảng được thành lập. ...

Ngày mười bốn, tháng tám, năm một nghìn chín trăm bốn mươi lăm, ...
Nhật tuyên bố đầu hàng đồng minh, ...
chiến tranh thế giới thứ hai kết thúc. ...
Thời cơ đã đến, ...
ngày mười sáu, tháng tám, năm một nghìn chín trăm bốn mươi lăm, ...
Đại hội Quốc dân họp ở Tân Trào. ...
Các tỉnh, thành phố thuộc đồng bằng Bắc Bộ ...
chỉ trong bảy ngày, ...
đã nổi dậy tổng khởi nghĩa giành thắng lợi. ...
Cách mạng tháng Tám thành công, ...
ngày hai, tháng chín, năm một nghìn chín trăm bốn mươi lăm, ...
tại Quảng trường Ba Đình, ...
Chủ tịch Hồ Chí Minh đọc bản Tuyên ngôn độc lập ...
khai sinh ra Nước Việt nam Dân chủ cộng hòa. ...

Ngày ba mươi mốt, tháng mười, năm một nghìn chín trăm bốn mươi lăm, ...
các chiến khu được thành lập. ...
Trong phạm vi đồng bằng Bắc Bộ và phụ cận ...
có các chiến khu: Chiến khu hai, Chiến khu ba và Chiến khu mười một. ...

Tiền thân từ các Chiến khu hai, ba và mười một ...
ra đời ngày ba mươi mốt, tháng mười, năm một nghìn chín trăm bốn mươi lăm, ...
qua nhiều lần sáp nhập, chia tách với các tên gọi khác nhau: ...
Ngày hai lăm, tháng giêng, năm một nghìn chín trăm bốn mươi tám ...
sáp nhập thành Liên khu ba; ...
tháng năm, năm một nghìn chín trăm năm mươi hai, ...
chia tách thành Khu ba và Khu Tả Ngạn; ...
tháng mười một, năm một nghìn chín trăm năm mươi lăm, ...
thành lập Quân khu Hữu Ngạn và Quân khu Tả Ngạn; ...
tháng năm, năm một nghìn chín trăm bảy mươi sáu ...
hợp nhất thành Quân khu ba. ...
Mặc dù đã nhiều lần thay đổi tên gọi khác nhau, ...
nhưng ngày ba mươi mốt, tháng mười, năm một nghìn chín trăm bốn mươi lăm ...
được xác định là Ngày thành lập, Ngày truyền thống ...
của Lực lượng Vũ trang Quân khu ba. ...

Bộ Tư lệnh Quân khu ba ...
hiện nay đứng chân ở phường Kiến An, Thành phố Hải Phòng. ...

Quân khu ba ...
không chỉ là nơi có nhiều căn cứ kháng chiến ...
mà còn là nơi có kinh đô ...
gắn liền với quá trình xây dựng, phát triển của ba Triều đại phong kiến. ...
Đó là cố đô Hoa Lư thuộc tỉnh Ninh Bình, ...
là kinh đô của ba Triều đại gồm: ...
Nhà Đinh, nhà Tiền Lê và nhà Lý. ...

Quân khu ba ...
là mảnh đất giàu truyền thống đấu tranh cách mạng; ...
trong cuộc kháng chiến chống Pháp và chống Mỹ, ...
nhân dân và Lực lượng Vũ trang Liên khu ba ...
đã phối hợp với đơn vị chủ lực ...
đánh hơn bảy mươi tám nghìn sáu trăm trận lớn nhỏ, ...
loại khỏi vòng chiến đấu gần bốn trăm nghìn tên địch, ...
phá hủy và thu giữ ...
bốn mươi hai nghìn súng các loại, ...
hàng trăm ngàn phương tiện chiến tranh. ...

Trong cuộc chiến đánh trả máy bay, tàu chiến Mỹ ...
đã đánh ba mươi chín nghìn bốn trăm năm mươi trận, ...
bắn rơi một nghìn năm trăm hai mươi sáu máy bay Mỹ; ...
bắt sống nhiều giặc lái; ...
tháo gỡ gần sáu mươi chín nghìn quả bom, mìn, thủy lôi, ...
phá tan chiến dịch phong tỏa đường biển vào cảng Hải Phòng. ...

Cùng với quân và dân miền Bắc ...
đánh đòn quyết định làm nên Điện Biên Phủ trên không ...
tháng mười hai năm một nghìn chín trăm bảy mươi hai đầy oanh liệt, ...
đánh thắng hoàn toàn hai cuộc chiến tranh phá hoại của Đế quốc Mỹ. ..."""

def generate(text, filename):
    print(f"Generating {filename}...")
    print(f"Text length: {len(text)} characters")
    engine = pyttsx3.init()
    engine.setProperty('rate', RATE)
    
    voices = engine.getProperty('voices')
    voice_found = False
    for voice in voices:
        if VOICE_NAME in voice.name or VOICE_NAME in voice.id:
            engine.setProperty('voice', voice.id)
            print(f"Using voice: {voice.name}")
            voice_found = True
            break
    
    if not voice_found:
        print(f"Warning: Voice '{VOICE_NAME}' not found. Using default.")

    import pythoncom
    try:
        pythoncom.CoInitialize()
        engine.save_to_file(text, filename)
        engine.runAndWait()
        del engine
    except Exception as e:
        print(f"Error: {e}")
    finally:
        pythoncom.CoUninitialize()
        
    print(f"Done: {filename}")

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.join(base_dir, "data", "audio_static")
    os.makedirs(output_dir, exist_ok=True)
    
    generate(TEXT_LICH_SU_QK3_FULL, os.path.join(output_dir, "lich_su_quan_khu_3.wav"))

if __name__ == "__main__":
    main()
