import os
import pyttsx3

# Config
VOICE_NAME = "Microsoft An"
RATE = 140

# Text with pauses
TEXT_MOC_SON = """Những mốc son lịch sử quân đội nhân dân Việt Nam. ...

Đội Việt Nam tuyên truyền giải phóng quân ...
thành lập ngày hai hai, tháng mười hai, năm một nghìn chín trăm bốn mươi bốn, ...
tại khu rừng giữa hai tổng Hoàng Hoa Thám và Trần Hưng Đạo ...
thuộc châu Nguyên Bình, tỉnh Cao Bằng. ...
Trung ương Đảng và Chủ tịch Hồ Chí Minh ...
đã giao cho đồng chí Võ Nguyên Giáp tổ chức lãnh đạo và tuyên bố thành lập Đội. ...
Đội gồm ba mươi bốn người, chia làm ba tiểu đội, có chi bộ Đảng lãnh đạo. ...
Sau lễ thành lập, toàn đội đã ăn một bữa cơm trắng, không rau, không muối ...
để tượng trưng cho tinh thần chịu đựng gian khổ của người chiến sĩ cách mạng. ...
Ngày hai hai, tháng mười hai, năm một nghìn chín trăm bốn mươi bốn, ...
được lấy làm Ngày thành lập Quân đội nhân dân Việt Nam. ...

Chiến thắng Phay Khắt, Nà Ngần, ...
ngày hai năm, tháng mười hai, năm một nghìn chín trăm bốn mươi bốn, ...
Đội Việt Nam tuyên truyền giải phóng quân ...
đã cải trang dùng mưu tập kích tiêu diệt đồn Phay Khắt, ...
mở đầu cho truyền thống đã ra quân là đánh thắng của Quân đội ta. ...

Đội du kích Ba Tơ, ...
thành lập ngày mười hai, tháng ba, năm một nghìn chín trăm bốn mươi lăm, ...
tại tỉnh Quảng Ngãi. ...

Việt Nam Giải phóng quân, ...
thành lập ngày mười lăm, tháng năm, năm một nghìn chín trăm bốn mươi lăm ...
tại đình Bằng Quảng, huyện Định Hóa, tỉnh Thái Nguyên. ...

Tổng khởi nghĩa tháng tám năm một nghìn chín trăm bốn mươi lăm ...
giành thắng lợi, ...
đã mở đường cho dân tộc Việt Nam bước vào kỷ nguyên độc lập, tự do. ...

Toàn quốc kháng chiến bùng nổ ...
ngày mười chín, tháng mười hai, năm một nghìn chín trăm bốn mươi sáu. ...

Chiến dịch Việt Bắc ...
từ ngày bảy, tháng mười, đến ngày hai mươi, tháng mười hai, năm một nghìn chín trăm bốn mươi bảy. ...

Chiến dịch Biên giới Thu Đông ...
từ ngày mười sáu, tháng chín, năm một nghìn chín trăm năm mươi ...
đến ngày mười bốn, tháng mười, năm một nghìn chín trăm năm mươi. ...

Chiến dịch Điện Biên Phủ ...
từ ngày mười ba, tháng ba, đến ngày bảy, tháng năm, năm một nghìn chín trăm năm mươi bốn. ...

Tổng tiến công nổi dậy Xuân Mậu Thân ...
năm một nghìn chín trăm sáu mươi tám. ...

Chiến dịch đường mười bốn, Phước Long ...
từ ngày mười ba, tháng mười hai, năm một nghìn chín trăm bảy mươi bốn ...
đến ngày sáu, tháng giêng, năm một nghìn chín trăm bảy mươi lăm. ...

Chiến dịch Tây Nguyên ...
từ ngày bốn, tháng ba, đến ngày ba, tháng tư, năm một nghìn chín trăm bảy mươi lăm. ...

Chiến dịch Hồ Chí Minh, ...
từ ngày hai sáu, đến ngày ba mươi, tháng tư, năm một nghìn chín trăm bảy mươi lăm, ...
kết thúc thắng lợi cuộc kháng chiến chống Mỹ cứu nước, ...
giải phóng hoàn toàn miền Nam, thống nhất Tổ quốc. ..."""

def generate(text, filename):
    print(f"Generating {filename}...")
    engine = pyttsx3.init()
    engine.setProperty('rate', RATE)
    
    voices = engine.getProperty('voices')
    voice_found = False
    for voice in voices:
        if VOICE_NAME in voice.name or VOICE_NAME in voice.id:
            engine.setProperty('voice', voice.id)
            print(f"Using voice: {voice.name}")
            voice_found = True
            break
    
    if not voice_found:
        print(f"Warning: Voice '{VOICE_NAME}' not found. Using default.")

    import pythoncom
    try:
        pythoncom.CoInitialize()
        engine.save_to_file(text, filename)
        engine.runAndWait()
        del engine
    except Exception as e:
        print(f"Error: {e}")
    finally:
        pythoncom.CoUninitialize()
        
    print(f"Done: {filename}")

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.join(base_dir, "data", "audio_static")
    os.makedirs(output_dir, exist_ok=True)
    
    generate(TEXT_MOC_SON, os.path.join(output_dir, "moc_son_lich_su.wav"))

if __name__ == "__main__":
    main()
