import os
import pyttsx3

# Config
VOICE_NAME = "Microsoft An"
RATE = 140

# Text with pauses
TEXT_TRUYEN_THONG = """Chín truyền thống của Quân đội nhân dân Việt Nam. ...

Một. . . ...
Trung thành vô hạn với Tổ quốc Việt Nam xã hội chủ nghĩa, ...
với Đảng, Nhà nước và nhân dân. ...

Hai. . . ...
Quyết chiến, quyết thắng, biết đánh, biết thắng. ...

Ba. . . ...
Gắn bó máu thịt với nhân dân, ...
quân với dân một ý chí. ...

Bốn. . . ...
Đoàn kết nội bộ, ...
cán bộ, chiến sĩ bình đẳng về quyền lợi và nghĩa vụ, ...
thương yêu giúp đỡ nhau, ...
trên dưới đồng lòng, thống nhất ý chí và hành động. ...

Năm. . . ...
Kỷ luật tự giác, nghiêm minh. ...

Sáu. . . ...
Độc lập tự chủ, tự lực, tự cường, ...
cần kiệm xây dựng quân đội, xây dựng đất nước, ...
tôn trọng và bảo vệ của công. ...

Bảy. . . ...
Lối sống trong sạch, lành mạnh, có văn hóa, ...
trung thực, khiêm tốn, giản dị, lạc quan. ...

Tám. . . ...
Luôn luôn nêu cao tinh thần ham học, cầu tiến bộ, ...
nhạy cảm, tinh tế trong cuộc sống. ...

Chín. . . ...
Đoàn kết quốc tế trong sáng, ...
thủy chung, chí nghĩa, chí tình. ..."""

def generate(text, filename):
    print(f"Generating {filename}...")
    engine = pyttsx3.init()
    engine.setProperty('rate', RATE)
    
    voices = engine.getProperty('voices')
    voice_found = False
    for voice in voices:
        if VOICE_NAME in voice.name or VOICE_NAME in voice.id:
            engine.setProperty('voice', voice.id)
            print(f"Using voice: {voice.name}")
            voice_found = True
            break
    
    if not voice_found:
        print(f"Warning: Voice '{VOICE_NAME}' not found. Using default.")

    import pythoncom
    try:
        pythoncom.CoInitialize()
        engine.save_to_file(text, filename)
        engine.runAndWait()
        del engine
    except Exception as e:
        print(f"Error: {e}")
    finally:
        pythoncom.CoUninitialize()
        
    print(f"Done: {filename}")

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.join(base_dir, "data", "audio_static")
    os.makedirs(output_dir, exist_ok=True)
    
    generate(TEXT_TRUYEN_THONG, os.path.join(output_dir, "9_truyen_thong.wav"))

if __name__ == "__main__":
    main()
