import os
import pyttsx3

# Config
VOICE_NAME = "Microsoft An"
RATE = 128  # Slightly slower for long historical content

# Full text from original file
TEXT_LICH_SU_TD8 = """Lịch sử ra đời của Trung đoàn tám. ...

Trung đoàn tám ...
thành lập ngày mười hai, tháng hai, năm một nghìn chín trăm bảy mươi mốt ...
tại thôn Khe Cắt, xã Minh Thành, huyện Yên Hưng, ...
nay là thị xã Quảng Yên, tỉnh Quảng Ninh. ...

Trong hoàn cảnh cuộc kháng chiến chống Mỹ cứu nước ...
của nhân dân ta đang diễn ra gay go, quyết liệt. ...

Với nhiệm vụ chính trị ban đầu ...
là tuyển quân và huấn luyện quân tăng cường, ...
sẵn sàng cơ động chiến đấu chi viện cho chiến trường miền Nam. ...

Trung đoàn tám được thành lập theo quyết định số bốn hai ...
ngày mười hai, tháng hai, năm một nghìn chín trăm bảy mươi mốt, ...
do Thiếu tướng Nguyễn Đôn, Thứ trưởng Bộ Quốc Phòng ký ...
thay Bộ trưởng Bộ Quốc Phòng. ...

Trung đoàn tám khi mới thành lập ...
đặt dưới sự chỉ đạo trực tiếp của Quân khu ủy ...
và Bộ Tư Lệnh Quân khu Tả Ngạn. ...

Trải qua hơn năm mươi lăm năm xây dựng, chiến đấu và trưởng thành, ...
Trung đoàn luôn phát huy bản chất cách mạng ...
và truyền thống vẻ vang của Bộ đội cụ Hồ, ...
hoàn thành tốt các nhiệm vụ được giao. ...

Các thế hệ cán bộ, chiến sĩ Trung đoàn ...
đã viết lên truyền thống: ...
Đoàn Kết, Xây Dựng Giỏi, Đi Tốt, Đánh Thắng. ...

Giai đoạn từ năm một nghìn chín trăm bảy mươi mốt ...
đến năm một nghìn chín trăm bảy mươi lăm: ...
Trung đoàn ra đời, ...
làm nhiệm vụ tuyển quân và huấn luyện quân tăng cường, ...
sẵn sàng cơ động chiến đấu chi viện cho các chiến trường miền Nam. ...

Trong bốn năm, ...
Trung đoàn đã xây dựng được ba mươi hai tiểu đoàn, ...
trong đó có một tiểu đoàn chiến sĩ gái ...
và một trung đoàn hoàn chỉnh, Trung đoàn sáu bốn. ...

Các đơn vị vào chiến trường ...
luôn đúng thời gian, đủ số lượng, đảm bảo chất lượng cao. ...

Nhiều đồng chí đã nhanh chóng trưởng thành trong chiến đấu, ...
phục vụ chiến đấu, ...
giữ những cương vị lãnh đạo chủ chốt. ...

Tiêu biểu là Trung đoàn sáu bốn, ...
tiền thân là Trung đoàn tám, Quân khu Tả Ngạn, ...
đã lập công lớn tại chiến trường miền Nam. ...

Giai đoạn từ năm một nghìn chín trăm bảy mươi lăm ...
đến năm một nghìn chín trăm bảy mươi tám: ...
Trung đoàn thực hiện nhiệm vụ xây dựng kinh tế ...
kết hợp với củng cố Quốc phòng trên vùng Đông Bắc của Tổ quốc. ...

Trong suốt ba năm liên tục ...
làm nhiệm vụ xây dựng kinh tế, ...
kết hợp với xây dựng địa bàn chính trị, ...
củng cố quốc phòng tại vùng rẻo cao Đông Bắc tỉnh Quảng Ninh, ...
cán bộ, chiến sĩ Trung đoàn tám ...
luôn quán triệt sâu sắc và chấp hành nghiêm chỉnh ...
các chỉ thị, nghị quyết của Trung ương Đảng. ...

Toàn Trung đoàn đã xây dựng được ...
hai trăm bốn mươi hai kilômét đường giao thông cấp ba và cấp bốn, ...
bảo đảm cho các hoạt động quân sự và dân sinh lâu dài. ...

Cùng với quá trình làm đường giao thông, ...
Trung đoàn còn xây dựng được ...
ba mươi chín cầu, cống các loại, ...
hai trạm thuỷ điện có công suất từ hai trăm đến ba trăm kilôoát, ...
trồng được hai nghìn một trăm hecta rừng cây công nghiệp và cây lấy gỗ. ...

Do lập được nhiều thành tích khá toàn diện ...
nên trong ba năm từ một nghìn chín trăm bảy mươi lăm ...
đến một nghìn chín trăm bảy mươi tám, ...
Trung đoàn tám đã được Nhà nước tặng thưởng ...
Huân chương Chiến công hạng Nhất. ...

Ủy ban nhân dân tỉnh Quảng Ninh tặng cờ ...
Đơn vị khá nhất trong phong trào phát triển kinh tế ...
kết hợp với củng cố quốc phòng. ...

Tổng cục Chính trị tặng cờ ...
Đơn vị có phong trào thanh niên khá nhất ...
ba năm liền một nghìn chín trăm bảy mươi lăm, bảy mươi sáu, bảy mươi bảy. ...

Giai đoạn từ năm một nghìn chín trăm bảy mươi chín ...
đến năm một nghìn chín trăm tám mươi sáu: ...
Trung đoàn làm nhiệm vụ sẵn sàng chiến đấu ...
và chiến đấu bảo vệ Tổ quốc. ...

Từ năm một nghìn chín trăm bảy mươi tám ...
đến năm một nghìn chín trăm tám mươi sáu, ...
Trung đoàn làm nhiệm vụ phòng ngự hướng quan trọng của Sư đoàn ...
sẵn sàng cơ động chiến đấu trên tuyến một ...
vùng Đông Bắc Tổ quốc, ...
đã hoàn thành tốt mọi nhiệm vụ được giao. ...

Đã phối hợp công tác với các đơn vị bạn ...
và Đảng bộ, chính quyền, nhân dân địa phương ...
xây dựng thành công pháo đài quân sự xã, huyện biên giới Bình Liêu, ...
không ngừng lớn mạnh ...
làm thất bại mọi âm mưu thủ đoạn lấn chiếm của đối phương. ...

Đặc biệt là Tiểu đoàn hai ...
đã lập được nhiều thành tích xuất sắc trong chiến đấu bảo vệ Tổ quốc ...
góp phần tô thắm truyền thống cách mạng vẻ vang của Trung đoàn và Sư đoàn. ...

Tiêu biểu là đội văn nghệ xung kích của Trung đoàn ...
thường xuyên duy trì hoạt động phục vụ bộ đội ở các điểm tựa ...
và đồng bào các dân tộc vùng sâu, vùng xa. ...

Phong trào văn nghệ ở Trung đoàn tám ...
thực sự là điểm sáng văn hóa, ...
có ảnh hưởng rộng lớn tại khu vực Đông Bắc, Quảng Ninh. ...

Giai đoạn từ năm một nghìn chín trăm tám mươi bảy ...
đến năm hai nghìn mười: ...
Xây dựng Đảng bộ hoàn thành xuất sắc nhiệm vụ ...
kết hợp xây dựng Trung đoàn vững mạnh toàn diện ...
trong thời kỳ đổi mới. ...

Thực hiện kế hoạch điều chỉnh thế bố trí chiến lược ...
của Bộ Quốc phòng và Quân khu, ...
đầu tháng sáu năm một nghìn chín trăm chín mươi chín, ...
cán bộ, chiến sĩ Trung đoàn ...
lưu luyến chia tay cấp ủy, chính quyền và nhân dân ...
huyện Tiên Yên, tỉnh Quảng Ninh ...
trở về với sự đùm bọc, yêu thương ...
của cấp ủy, chính quyền và nhân dân ...
huyện Tiền Hải, tỉnh Thái Bình, nay là tỉnh Hưng Yên. ...

Kể từ ngày đầu đặt chân về Thái Bình, ...
quê hương có nền văn hiến lâu đời, ...
giàu truyền thống yêu nước, chống giặc ngoại xâm, ...
được sự quan tâm lãnh đạo, chỉ đạo ...
của Đảng uỷ, Bộ Tư lệnh Quân khu, ...
cán bộ, chiến sĩ Trung đoàn ...
thường xuyên quán triệt sâu sắc nhiệm vụ cách mạng, ...
nỗ lực phấn đấu vươn lên ...
hoàn thành toàn diện các nhiệm vụ chính trị. ...

Giai đoạn từ năm hai nghìn mười một đến nay: ...
Nhiệm vụ chính trị của Trung đoàn ...
là huấn luyện sẵn sàng chiến đấu, ...
cơ động nhận nhiệm vụ trên giao, ...
xây dựng Đảng bộ trong sạch vững mạnh, ...
Trung đoàn vững mạnh toàn diện, ...
tạo bước đột phá trong công tác huấn luyện. ...

Từ năm hai nghìn mười một đến nay ...
là giai đoạn Trung đoàn tiếp tục có những bước phát triển mới khá toàn diện. ...

Kế thừa và phát huy truyền thống ...
Đoàn kết, Xây dựng giỏi, Đi tốt, Đánh thắng, ...
cán bộ, chiến sĩ Trung đoàn ...
đã không ngừng nỗ lực, vươn lên ...
thực hiện tốt nhiệm vụ xây dựng đơn vị điểm về chính trị. ...

Từ năm hai nghìn mười chín, ...
Trung đoàn đã thực hiện tốt nhiệm vụ ...
xây dựng đơn vị điểm vững mạnh toàn diện ...
mẫu mực, tiêu biểu ...
theo sự chỉ đạo của Thường vụ Đảng ủy, ...
Thủ trưởng Bộ Tư lệnh Quân khu ba và chỉ huy Sư đoàn. ...

Trung đoàn luôn là lá cờ đầu trong công tác huấn luyện, ...
đơn vị tiêu biểu trong phong trào thi đua quyết thắng ...
của Quân khu và Sư đoàn. ..."""

def generate(text, filename):
    print(f"Generating {filename}...")
    print(f"Text length: {len(text)} characters")
    engine = pyttsx3.init()
    engine.setProperty('rate', RATE)
    
    voices = engine.getProperty('voices')
    voice_found = False
    for voice in voices:
        if VOICE_NAME in voice.name or VOICE_NAME in voice.id:
            engine.setProperty('voice', voice.id)
            print(f"Using voice: {voice.name}")
            voice_found = True
            break
    
    if not voice_found:
        print(f"Warning: Voice '{VOICE_NAME}' not found. Using default.")

    import pythoncom
    try:
        pythoncom.CoInitialize()
        engine.save_to_file(text, filename)
        engine.runAndWait()
        del engine
    except Exception as e:
        print(f"Error: {e}")
    finally:
        pythoncom.CoUninitialize()
        
    print(f"Done: {filename}")

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.join(base_dir, "data", "audio_static")
    os.makedirs(output_dir, exist_ok=True)
    
    generate(TEXT_LICH_SU_TD8, os.path.join(output_dir, "lich_su_trung_doan_8.wav"))

if __name__ == "__main__":
    main()
