import os
import pyttsx3

# Config
VOICE_NAME = "Microsoft An"
RATE = 130

# Full text from original file
TEXT_LICH_SU_SD395 = """Lịch sử hình thành Sư đoàn ba chín năm. ...

Phần một. Sư đoàn ba hai năm B, tiền thân của Sư đoàn ba chín năm ngày nay. ...

Ngày hai bảy, tháng giêng, năm một nghìn chín trăm bảy mươi ba, ...
Hiệp định chấm dứt chiến tranh lập lại hòa bình ở Việt nam ...
được ký tại Pari. ...
Sư đoàn ba hai năm B, trực thuộc Quân khu tả ngạn, ...
tiền thân Sư đoàn ba chín năm, ...
được thành lập theo Quyết định số hai hai hai ...
do Thứ trưởng Bộ Quốc Phòng, Thượng tướng  Hoàng Văn Thái ký ...
ngày hai sáu, tháng mười hai, năm một nghìn chín trăm bảy mươi bốn. ...

Địa điểm đứng chân đầu tiên của Sư đoàn ...
là huyện Lục Nam, tỉnh Hà Bắc. ...
Sở chỉ huy đóng quân ở khu vực Đồi Ngô, xã Tiên Hưng. ...

Địa điểm đứng chân hiện nay: ...
Thị xã Quảng Yên, Tỉnh Quảng Ninh. ...

Phần hai. Sư đoàn ba hai năm B thực hiện nhiệm vụ tuyển quân, ...
huấn luyện quân chi viện cho chiến trường miền Nam. ...

Đợt một: ...
Ngày hai mươi, tháng giêng, năm một nghìn chín trăm bảy mươi lăm, ...
đợt đầu tiên phải tuyển mười Tiểu đoàn ...
hoàn thành trước ngày hai lăm, tháng giêng, năm một nghìn chín trăm bảy mươi lăm. ...

Đợt hai: ...
Sư đoàn được giao nhiệm vụ tuyển mười ba Tiểu đoàn có bảy trăm nữ, ...
phải xong trước ngày hai lăm, tháng hai, năm một nghìn chín trăm bảy mươi lăm. ...

Đợt ba: ...
Sư đoàn được giao nhiệm vụ tuyển sáu Tiểu đoàn ...
và tổ chức lên đường vào tháng tư, năm một nghìn chín trăm bảy mươi lăm. ...

Như vậy trong thời gian ngắn ...
từ đầu tháng giêng đến tháng tư, năm một nghìn chín trăm bảy mươi lăm, ...
Sư đoàn đã tuyển và huấn luyện được hai mươi chín Tiểu đoàn tân binh, ...
tương đương với hai Sư đoàn bộ binh. ...
Trong đó, tổ chức đi chiến đấu ở chiến trường miền Nam ...
được mười nghìn năm trăm tám mươi chín người. ...

Phần ba. Sư đoàn chuyển sang làm nhiệm vụ xây dựng kinh tế ...
kết hợp với củng cố quốc phòng trên hướng Đông Bắc của Tổ quốc. ...

Từ năm một nghìn chín trăm bảy mươi sáu ...
đến năm một nghìn chín trăm bảy mươi tám, ...
Sư đoàn làm nhiệm vụ xây dựng kinh tế ...
kết hợp với củng cố quốc phòng ...
tại khu vực: Bình liêu, Quảng Hà, Ba Chẽ, Tiên Yên. ...
Đã mở được hàng chục tuyến đường với chiều dài hai trăm năm mươi kilômét. ...
Cùng nhân dân đắp hồ: Yên Lập; Quảng Long; Voong Lá; Quất Đông, Hải Lạng. ...

Phần bốn. Sư đoàn làm nhiệm vụ chiến đấu bảo vệ biên giới Đông Bắc của Tổ quốc ...
từ năm một nghìn chín trăm bảy mươi tám ...
đến tháng mười hai năm một nghìn chín trăm tám mươi sáu. ...

Năm một nghìn chín trăm bảy mươi tám, ...
tình hình biên giới phía Tây Nam và phía Bắc của đất nước ...
có những diễn biến phức tạp. ...

Tháng năm, năm một nghìn chín trăm bảy mươi tám, ...
Bộ tư lệnh quân khu quyết định tách Trung đoàn bốn ba ...
của Sư đoàn ba hai năm B về thuộc Tỉnh đội Quảng Ninh, ...
đồng thời điều Trung đoàn tám thuộc Quân khu ba ...
về nhập đội hình Sư đoàn ba hai năm B thay Trung đoàn bốn ba. ...

Ngày hai mươi, tháng bảy, năm một nghìn chín trăm bảy mươi tám, ...
Trung đoàn Pháo binh liên hợp được thành lập ...
mang phiên hiệu Trung đoàn một tám chín. ...

Cuối tháng mười hai, năm một nghìn chín trăm bảy mươi tám, ...
bộ tư lệnh Sư đoàn tổ chức giao nhiệm vụ cho các đơn vị: ...
Trung đoàn bốn hai phòng ngự trên hướng chủ yếu của Sư đoàn. ...
Trung đoàn hai tám tám phòng ngự trên hướng quan trọng. ...
Trung đoàn tám làm lực lượng cơ động của Sư đoàn. ...

Trải qua gần hai mươi ngày đêm chiến đấu kiên cường bất khuất bền bỉ ...
từ ngày mười chín, tháng hai, năm một nghìn chín trăm bảy mươi chín ...
đến ngày năm, tháng ba, năm một nghìn chín trăm bảy mươi chín, ...
các đơn vị phòng ngự giữ vững trận địa ...
bảo vệ vững chắc lãnh thổ, chủ quyền của Tổ quốc. ...

Do yêu cầu nhiệm vụ, ...
ngày bốn, tháng năm, năm một nghìn chín trăm bảy mươi chín, ...
bộ quốc phòng quyết định thay đổi phiên hiệu ...
Sư đoàn ba hai năm B thành Sư đoàn ba chín năm ...
theo quyết định số năm ba không do thứ trưởng Bộ Quốc phòng Lê Trọng Tấn ký. ...

Phần năm. Xây dựng Sư đoàn cách mạng, chính quy, tinh nhuệ, ...
từng bước hiện đại, hoàn thành mọi nhiệm vụ. ...

Ngày mười bốn, tháng tám, năm một nghìn chín trăm tám mươi bảy, ...
Đảng ủy Quân sự trung ương ra Nghị quyết số một năm bốn ...
quyết định hợp nhất Đặc khu Quảng Ninh vào Quân khu ba, ...
theo đó Sư đoàn ba chín năm thuộc sự lãnh đạo chỉ huy của Bộ tư lệnh Quân khu ba. ...

Tháng mười một, năm một nghìn chín trăm tám mươi bảy, ...
Trung đoàn bốn hai tách khỏi đội hình Sư đoàn ...
về trực thuộc Bộ chỉ huy Quân sự tỉnh Quảng Ninh. ...

Tháng mười hai, năm một nghìn chín trăm tám mươi bảy, ...
Sư đoàn tiếp nhận Trung đoàn bộ binh hai thuộc Sư đoàn ba hai tám. ...

Từ khi trực thuộc Quân khu ba, ...
nhiệm vụ của Sư đoàn cũng có sự thay đổi, ...
Sư đoàn làm nhiệm vụ cơ động sẵn sàng chiến đấu. ...

Đầu năm một nghìn chín trăm chín mươi mốt, ...
bộ tư lệnh quân khu ba triển khai kế hoạch ...
về chia lại toàn bộ đội hình Sư đoàn ba chín năm. ...

Ngày hai lăm, tháng năm, năm một nghìn chín trăm chín mươi mốt, ...
Sư đoàn tiến hành giải thể Trung đoàn Pháo binh một tám chín ...
và ngày năm, tháng bảy, năm một nghìn chín trăm chín mươi mốt, ...
giải thể Trung đoàn tám tám. ...

Ngày ba, tháng tư, năm một nghìn chín trăm chín mươi sáu, ...
bộ tư lệnh quân khu ba ra quyết định ...
về kiện toàn biên chế tổ chức Sư đoàn ba chín năm. ...
Đến tháng năm, năm một nghìn chín trăm chín mươi sáu, ...
Sư đoàn tổ chức tiếp nhận Trung đoàn bốn ba ...
từ Bộ Chỉ huy quân sự tỉnh Quảng Ninh. ...
Như vậy, sau mười tám năm, ...
lần thứ hai Trung đoàn bốn ba trở về với Sư đoàn. ...

Phần sáu. Xây dựng Sư đoàn vững mạnh toàn diện ...
thời kỳ đẩy mạnh công nghiệp hóa, hiện đại hóa đất nước ...
từ tháng giêng, năm hai nghìn đến nay. ...

Giai đoạn hiện nay, ...
Sư đoàn tiếp tục thực hiện nhiệm vụ sẵn sàng chiến đấu, ...
huấn luyện, nâng cao sức mạnh chiến đấu và chất lượng tổng hợp, ...
xây dựng Sư đoàn vững mạnh toàn diện. ...

Hiện nay các đơn vị trong Sư đoàn ...
đứng chân trên địa bàn thuộc ba tỉnh ...
Quảng Ninh, Hải Phòng, Hưng Yên. ...

Sư đoàn luôn hoàn thành xuất sắc mọi nhiệm vụ mà Bộ và Quân khu giao. ...

Phần bảy. Những phần thưởng cao quý ...
của Đảng, Nhà nước trao tặng cho Sư đoàn ba chín năm. ...

Với những thành tích đặc biệt xuất sắc ...
hơn bốn mươi tám năm qua, ...
cán bộ, chiến sỹ Sư đoàn đã được Đảng, Nhà nước trao: ...

Một Huân chương quân công hạng Nhất. ...
Một Huân chương chiến công hạng Nhì. ...
Một Huân chương chiến công hạng Ba. ...
Một Huân chương bảo vệ Tổ quốc hạng Nhì. ...
Một Huân chương bảo vệ Tổ quốc hạng ba năm hai nghìn mười bốn. ...
Cờ Thi đua Chính phủ. ...

Hàng trăm cờ thi đua, bằng khen, giấy khen ...
của bộ quốc phòng, bộ tư lệnh quân khu, ...
cấp ủy và chính quyền địa phương. ...

Mười bốn tập thể được tặng thưởng Huân chương chiến công các hạng. ...
Hai trăm lẻ bảy cá nhân được tặng huân, huy chương các loại. ...
Đã có ba mươi bảy tướng lĩnh quân đội trưởng thành từ Sư đoàn. ...

Có ba đơn vị được phong tặng danh hiệu ...
Anh hùng lực lượng vũ trang nhân dân thời kỳ đổi mới: ...

Ngày hai, tháng mười một, năm hai nghìn lẻ một, ...
Trung đoàn bốn ba được phong tặng danh hiệu ...
Anh hùng lực lượng vũ trang nhân dân trong thời kỳ đổi mới. ...

Ngày một, tháng hai, năm hai nghìn lẻ hai, ...
Trung đoàn hai được phong tặng danh hiệu ...
Anh hùng lực lượng vũ trang nhân dân ...
trong kháng chiến chống Mỹ cứu nước. ...

Ngày hai mươi mốt, tháng mười hai, năm hai nghìn lẻ năm, ...
Tiểu đoàn mười chín Công binh ...
được phong tặng danh hiệu ...
Anh hùng lực lượng vũ trang nhân dân trong thời kỳ đổi mới. ..."""

def generate(text, filename):
    print(f"Generating {filename}...")
    print(f"Text length: {len(text)} characters")
    engine = pyttsx3.init()
    engine.setProperty('rate', RATE)
    
    voices = engine.getProperty('voices')
    voice_found = False
    for voice in voices:
        if VOICE_NAME in voice.name or VOICE_NAME in voice.id:
            engine.setProperty('voice', voice.id)
            print(f"Using voice: {voice.name}")
            voice_found = True
            break
    
    if not voice_found:
        print(f"Warning: Voice '{VOICE_NAME}' not found. Using default.")

    import pythoncom
    try:
        pythoncom.CoInitialize()
        engine.save_to_file(text, filename)
        engine.runAndWait()
        del engine
    except Exception as e:
        print(f"Error: {e}")
    finally:
        pythoncom.CoUninitialize()
        
    print(f"Done: {filename}")

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.join(base_dir, "data", "audio_static")
    os.makedirs(output_dir, exist_ok=True)
    
    generate(TEXT_LICH_SU_SD395, os.path.join(output_dir, "lich_su_su_doan_395.wav"))

if __name__ == "__main__":
    main()
